import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

String generateRandomFileName({int length = 10}) {
  final randomBytes = _generateRandomBytes(length);
  final base64String = base64Url.encode(randomBytes);
  return 'file_$base64String';
}

Uint8List _generateRandomBytes(int length) {
  final random = Random.secure();
  // this line of code below generates a list of random integers (values) with a
  //length specified by the length parameter. Each integer is generated by
  //the random.nextInt(256) expression, ensuring that the integers are
  //between 0 and 255 (inclusive) in this case
  final List<int> values =
      List.generate(length, (index) => random.nextInt(256));
  return Uint8List.fromList(values);
}
